version: '3.6'

services:
  bnb:
    restart: always
    image: "bnb-proxy:0.1"
    ports:
      - "10000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  fantom:
    restart: always
    image: "fantom-proxy:0.1"
    ports:
      - "20000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  tron:
    restart: always
    image: "tron-proxy:0.1"
    ports:
      - "30000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  arbitrum:
    restart: always
    image: "arbitrum-proxy:0.1"
    ports:
      - "40000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  avalance:
    restart: always
    image: "avalance-proxy:0.1"
    ports:
      - "50000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  peta:
    restart: always
    image: "peta-proxy:0.1"
    ports:
      - "60000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  ether:
    restart: always
    image: "ether-proxy:0.1"
    ports:
      - "55000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  bnb-mainnet:
    restart: always
    image: "bnb-mainnet-proxy:0.1"
    ports:
      - "25000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"