version: '3.6'

services:
  specta:
    restart: always
    image: "specta:0.1"
    ports:
      - "10000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  fantom:
    restart: always
    image: "fantom:0.1"
    ports:
      - "20000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"